# Generated by Django 4.2 on 2024-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjoincourse',
            name='joined_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
