# Generated by Django 4.2 on 2024-04-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentscoredetail',
            unique_together={('score_column', 'student_join_course')},
        ),
    ]
