# Generated by Django 4.2 on 2024-04-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_lecturer_delete_student_lecturer_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='is_lecturer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
    ]
