# Generated by Django 4.2 on 2024-04-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lecturer_options_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.course'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
