# Generated by Django 4.2 on 2024-05-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatKey',
        ),
    ]
