# Generated by Django 4.2 on 2024-05-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatkey',
            name='key',
        ),
    ]
