# Generated by Django 4.2 on 2024-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_chatkey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatkey',
            name='key',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
